### ISSUE TITLE
No setting the seed value after creation?

### ISSUE THREAD

**Issue by JG-Adams** [Reputeless/Xoshiro-cpp#5]
I'd like to be able to modify the seed number during runtime. It's a useful utility. Is this RNG good for that?

setSeed(int64_t)
getSeed() return int64_t

**Comment by drohmf** [comment]
To re-seed, you can assign a new instance with the desired seed:

```cpp
auto rng = Xoshiro::Xoshiro256Plus( 1234 );
//... use rng ...

rng = Xoshiro::Xoshiro256Plus( 6789 );
//... use rng with the new seed ...
```

---

It's unlikely that methods like `setSeed`/`getSeed` would be added here. Xoshiro generators were [designed](https://prng.di.unimi.it/) for high performance contexts, keeping the minimal state required to run the generator. Storing the seed in every generator would likely be seen as an unwelcome overhead.

You can track the seed separately, as shown in the [examples](https://github.com/Reputeless/Xoshiro-cpp#examples); or use a wrapper class to store the seed, something like:

```cpp
template <class Generator>
struct Seedful : Generator
{
    using seed_type = std::uint64_t;

    constexpr explicit Seedful(seed_type seed = XoshiroCpp::DefaultSeed) noexcept
        : Generator(seed), m_seed(seed)
    {}

    constexpr void setSeed(seed_type seed)
    {
        m_seed = seed;
        this->deserialize(Generator(seed).serialize());
    }

    [[nodiscard]] 
    constexpr seed_type getSeed() const noexcept 
    { 
        return m_seed;
    }

  private:
    seed_type m_seed;
};
```

Usage:
```cpp
auto rngA = Seedful<XoshiroCpp::Xoshiro256Plus>( 1234 );
    
assert(rngA.getSeed() == 1234); 
for (int i : {1, 2, 3})  { std::cout << rngA() << "\n"; }
assert(rngA.getSeed() == 1234);

rngA.setSeed( 555 );
assert(rngA.getSeed() == 555); 

auto rngB = XoshiroCpp::Xoshiro256Plus( 555 );
for (int i: {1, 2, 3}) { assert(rngA() == rngB()); }

```

Full example on [godbolt](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGIaa4AMngMmAByPgBGmMQgAGykAA6oCoRODB7evv5JKWkCwaERLNGxCXaYDulCBEzEBJk%2BftIVVQI1dQSF4VEx8ba19Y3ZLYNdIT0lfXEAlLaoXsTI7BzmAMwhyN5YANQma26iCkr1%2B9gmGgCC65vbmHsHTgoExJisZxfXZhsMW167%2BzcxEM6FQLA%2BVxuvzuDzcCAIBESChAAHoUcCAO4AOmAhAQXkiXhOaEEjAIWLQLBRACVMIkvARMPRjiiABopBB4YioAC0yESiRRADcuFiuGyOVzUG4BViEAKIdcroyWIkDIzYVsmMcdgBxRgxJhEYiKnZmvbfPBUHYAfRt/O8CjVRIe5zWABEdmYNN6fYEdmidm5rNZvTsSctEgQdkRwwJnsCQnqDcDjZ9zRmdq8AI5eLmYBQ7Z7oEAgLwMK0kFg24EMUHVyKEG3AFNGkiA/WhVPttbnK4Z9auK2fBNeBw7ISYTDoKheWg7EDJrttk2QgDsVn75qJIWARan6BtBAAnol7vtPcXS3nBHFJEf9pulZcMyTnphVIliDsP2q8MhCAnA9Z1oCAlGnI9T3ucD0AeT12QUTluRlRJS3dTAqCYOdhAPGYdgYVAP0jAh00zM1F07Q1jTA3DSB2asYJo6cZlIs0TA3dj3U%2BVi4wYd9P2/IVUDwWClBw6cmMPE8z33ZiePYp8yLNBiDzg2T0EfHiMwITkFB5M4sBOPAxDwAAvTAIEo7tiEkmYsSMkzzIgGYWLWRTzU47itzYgBWKw/II/AFFEYgNJ8rjwr2bzeP4r91MgmSW3E9BnJi6MCKIulo3kjcopfJTXgIRYGHom0YM06LPMhLcvzwIUjXYHiYIS%2B4VOnCrrjXLi3K85830ZASdiEkS41VOhMEcNgjwLAhnO4jjop3Ix8NYAtEiYZYdgQpDpQVHrqvys1%2Bt/b8sNjWt0BfC8gOnEDAW2qUzB8uJlEdM4IC4b5JFc9yzWeI1/xtbUTlmi7LhxCbJwkvCL2uz61m%2BjqeOOwaztQLMQQsNSTD8nGuMqhbDszNGs2W66oZnOd7slbknpet7ew%2Br6fq081iCMOb9qJjN2eATnfszXn%2BdZs1CuK0ngA6gcuuF6L/scZAgeOGJQcxiHktS2GPR2eHEa53rX3jAa4pJi63Gx3HwpygWM1NsntYpu6Dge2nnteol3p8jQNBZ6KeY533ubZgOpYKkOuaUiX7Mhg8mYRwPI6FhOw755OyKT0P04m8XeczvYZbTotagVpWQYgM31YpzWPTh5mka63rPhCWgJiG4TYOIctJswabnjm9cBaWvdmDYJ0NvuF3dsSPOeJvAg7yPdS1N1vOrxQBZsoOQELTMHG3AYXmrod4CqedmnUDp92FHe9TF3MMxYW3mDH4OHedhYnz9/vvO7eAI/PUdqfNwk9L4M2wLZH%2Byt6jlyMODJKVcYY121jBH6A45YEBLOvBkL9zb3wpnfMwD9ATb0PpXWOiDgyv2/p/Bg38/aRxwW/CWlxnIEKIVvV%2Bh9q6UNwYQvetC%2BH0MjsQqhhDRawNYW/ER5suEUO3tQr%2Bgig7CI4bwh%2BzDJH30YbIxhCiBG7yEUpaRO98FSNUcwsh0NdF8Jod/CO5pgYqxgX/SxKVEHdUvLhJGi0Qjz3vOlTAGIyqqWul7DQq8MGljQNg4xejSFiSrrfMxPD8KBOCdOaxD8P6KN3vY8RLiEmx1CEElBkCy7xJiMZFuTl3HXRAW7R0EBinpPQHZBy1SLIuUfJmQMyAECVAANZFwalmGanQeKOOgaQ%2BB5C4LXWaaUvJRdMHRM3ikvBB42HaNga47h8ibE5JFkY8xWiNEzC2cYnRsSDn6KOWRa56jZEXPMVck5Ny6HKOOessRZznkpNed83eti%2BFLMmaDHZMyrFa09AsrxSy16rMyaYrRlyIUxyhW8oFhz9bRV/ljOp59QFEiaWkxZAsEUb0yfw3m%2BLtb1PpsSpJKLzGwoyQ89%2B/CPkMOET8mlmixGouABYPZoisW3MMQw05fLznJJIUYYVcjRWcqUdyoxvL5X8vYf8jViq1HKtyVjNi658bPl8fRJgIRNaE0NmNeg3de6zULp3QQeApqMj7oHTiHA5i0E4D5XgfgOBaFIKgTgwZLDWCLAsJY55vg8FIAQTQ3q5gDP8AADixJIDQABONcabJDZrWGmny2bCFpv0JwSQAak0hs4LwZEGgE1JrmHAWAMBEDrwYPwYgLBDDLHIJQSkiRxrEGRLAIdI6ACSJZgBri4CGqM6RkQcB5MWC8pgI2WC4Gub1pAIATvoMQadKADBGDCQuxw8ZOCroweukMW6d0toPTEY9Qp%2BSJBtCKbNNpvQ2lUHeC9S7OAoivBuqwD7d37rBMOw9x7gCfTMIBq9K610ejA6GLQLlSDTkICQESehT3AGPehyw%2Bg8CRDHc5H1frq1Bt4KGjgHgu1Vj7fcAAangQJMQdgQFwLh786wuB4UkCiLg/qm10aw/0pgWBYjOQrRwKtpAWAgDWHELEd4fKfTiD5SQaauDZriD6Uggbg0MfrSARtibJN7vbRAJAH5KgMhIAOiAdRgAKGUIYJkQgECoAxIG%2BNB6AYCC86EWgvn/Omd4M%2B2IWojCfW9qQWLYRVp1uS9BkdAB5BkkWAs1sc8gS4xAPPpcKzUfAgbeD8EECIMQ7ApAyEEIoFQ6g6OkF0IhwjKB702BbhR%2BAcxUCLuQzejSaHevbvrdG5YehiwhDCz5vz%2BXuC8BeFOSzpAMTAlQqt6jHBxPRdrRwbAqgnPGh2KoNNcQeR3nDIRnWZgsQaGezx8N4GbA7D4xdwTMw1vNrmNJ2TlAU0gB8k9otPk1iEJLWYLg8OS0KaUypuIawsRrF02mtcCMtNpo0GsbN5ajvmdsJt6zmHQdaaxCWn0YmNBxCkBoNc2OFNrFo2Z9L5Pk0KbMOz%2BjnOAekCFDEVIzhJBAA%3D).

**Comment by JG-Adams** [comment]
Very nice! :)
I don't really consider reallocating an object just to change the state a desirable thing. Wouldn't that be slower than to have mutable variable member?
I've concluded that this RNG may not be good for something like a world generator because some seeds would turn out ugly.
The use case is just to have randomness in general right? It is very fast for that.

**Comment by drohmf** [comment]
> I don't really consider reallocating an object just to change the state a desirable thing. Wouldn't that be slower than to have mutable variable member?

Normally, yes, for expensive objects. However, in this case, assigning a new instance is the efficient way, because:

1. Re-seeding a generator necessarily means restarting the state of the generator to use the seed from the beginning. That's exactly what the constructors for `XoshiroCpp::` generators do.
2. `XohiroCpp::` generators are small (64bit, 128bit, or 256bit). That's the size of 1 to 4 pointers (on 64-bit platforms).
3. You'll notice that all `XoshiroCpp::` methods and constructors are `constexpr`. So if the inputs (i.e. seeds) are known at compile time, then all these constructions (e.g. `Xoshiro::Xoshiro256Plus(6789)`) and member function calls (e.g.  `.serialize()`) will be done at compile time. Otherwise, if the inputs are dynamic, these methods and constructors will almost always get inlined by the optimizer without any "function call overhead" or "object instantiation overhead", effectively leaving you with the equivalent of directly mutating a member variable.

>The use case is just to have randomness in general right? It is very fast for that.

Yes, it strives to generate a uniform random distribution of unsigned numbers within the full range of bits. So a 64-bit generator would produce numbers in the range `[0, 2^64)`. 

The intended usage would be similar to how you would use [`std::mt19937_64`](https://en.cppreference.com/w/cpp/numeric/random/mersenne_twister_engine), for example. And you would typically want to feed those uniformly generated values to a distribution of your liking ([normal](https://en.cppreference.com/w/cpp/numeric/random/normal_distribution), [poisson](https://en.cppreference.com/w/cpp/numeric/random/poisson_distribution), [uniform](https://en.cppreference.com/w/cpp/numeric/random/uniform_int_distribution), etc.).

> ... some seeds would turn out ugly

This might be a little off topic for this thread, but you might find more "visually pleasing" randomness from something like https://github.com/Reputeless/PerlinNoise.

**Comment by JG-Adams** [comment]
Very interesting! Thanks for taking the time to teach me that! :)
